// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI80YjTB-eqz9OYjt2nl41_L4v3IV-UlE',
    appId: '1:161614075971:web:7b34f117f66a57dfae9cf6',
    messagingSenderId: '161614075971',
    projectId: 'sulthan-95049',
    authDomain: 'sulthan-95049.firebaseapp.com',
    storageBucket: 'sulthan-95049.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-baVpovRvReLBXokXdNNCHXCbduYgrw',
    appId: '1:161614075971:android:2e012c7a2f953a96ae9cf6',
    messagingSenderId: '161614075971',
    projectId: 'sulthan-95049',
    storageBucket: 'sulthan-95049.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1H9-tcBVEH-sdatmv0KFF-pLpherOqko',
    appId: '1:161614075971:ios:5d893eaca39643eeae9cf6',
    messagingSenderId: '161614075971',
    projectId: 'sulthan-95049',
    storageBucket: 'sulthan-95049.firebasestorage.app',
    iosBundleId: 'com.sulthan.sulthan',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1H9-tcBVEH-sdatmv0KFF-pLpherOqko',
    appId: '1:161614075971:ios:5d893eaca39643eeae9cf6',
    messagingSenderId: '161614075971',
    projectId: 'sulthan-95049',
    storageBucket: 'sulthan-95049.firebasestorage.app',
    iosBundleId: 'com.sulthan.sulthan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI80YjTB-eqz9OYjt2nl41_L4v3IV-UlE',
    appId: '1:161614075971:web:e0e6a49b5782450eae9cf6',
    messagingSenderId: '161614075971',
    projectId: 'sulthan-95049',
    authDomain: 'sulthan-95049.firebaseapp.com',
    storageBucket: 'sulthan-95049.firebasestorage.app',
  );
}
