// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2MsmjAdcpfrmhE-u3JpbF-eeeDaig20',
    appId: '1:400182855595:web:55bfd778d592f4db47f4ee',
    messagingSenderId: '400182855595',
    projectId: 'sult-b9b82',
    authDomain: 'sult-b9b82.firebaseapp.com',
    storageBucket: 'sult-b9b82.firebasestorage.app',
    measurementId: 'G-T83N309D14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuSlYnSPiOKeWPQm6Rmk3zWTxvcBl5KY',
    appId: '1:400182855595:android:351258463276440247f4ee',
    messagingSenderId: '400182855595',
    projectId: 'sult-b9b82',
    storageBucket: 'sult-b9b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXAtj0_zQPmDMWsan5GtcMEZNvUm3YRY',
    appId: '1:400182855595:ios:3e265c05c445996647f4ee',
    messagingSenderId: '400182855595',
    projectId: 'sult-b9b82',
    storageBucket: 'sult-b9b82.firebasestorage.app',
    iosBundleId: 'com.sulthan.sulthan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxXAtj0_zQPmDMWsan5GtcMEZNvUm3YRY',
    appId: '1:400182855595:ios:3e265c05c445996647f4ee',
    messagingSenderId: '400182855595',
    projectId: 'sult-b9b82',
    storageBucket: 'sult-b9b82.firebasestorage.app',
    iosBundleId: 'com.sulthan.sulthan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc2MsmjAdcpfrmhE-u3JpbF-eeeDaig20',
    appId: '1:400182855595:web:3889cd06919fad4c47f4ee',
    messagingSenderId: '400182855595',
    projectId: 'sult-b9b82',
    authDomain: 'sult-b9b82.firebaseapp.com',
    storageBucket: 'sult-b9b82.firebasestorage.app',
    measurementId: 'G-7KRHBN9WC1',
  );
}
